#!/usr/bin/env bash
# Script that transfers a file from
# our client to a server.

FilePath=$1
IPaddress=$2
UserName=$3
KeyPath=$4
if [ $# -lt 3 ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
elif [ $# -eq 3 ]; then
    scp -o StrictHostKeyChecking=no "$FilePath" "$UserName@$IPaddress:~/"
else
    scp -o StrictHostKeyChecking=no -i "$KeyPath" "$FilePath" "$UserName@$IPaddress:~/"
fi
