#!/usr/bin/env bash
# Configures 2nd server to work as 1st.

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/ /var/www/error
sudo chmod -R 755 /var/www
echo 'Hello World!' | sudo tee -a /var/www/html/index.html
echo -e "Ceci n'est pas une page" | sudo tee -a /var/www/error/404.html

ServerConf=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        
        location / {
                try_files \$uri \$uri/ =404;
                add_header X-Served-By \$hostname;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://github.com/SeasonLeague permanent;
        }
        error_page 404 /404.html;
        location = /404.html {
                root /var/www/error/;
                internal;
                add_header X-Served-By \$hostname;
        }
}"

sudo bash -c "echo -e '$ServerConf' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
        sudo service nginx start
else
        sudo service nginx restart
fi
