#!/usr/bin/env bash
# This script creates a file containing its own PID, displays "To infinity and beyond" indefinitely,
# handles SIGTERM and SIGINT signals, and deletes the PID file and terminates itself on SIGQUIT or SIGTERM
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'rm /var/run/myscript.pid; exit' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
