#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop, but for the 9th iteration,
# it displays "Best School" and then "Hi" on a new line.

i=1
while [ $i -le 10 ]; do
    if [ $i -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
