#!/usr/bin/env bash
# Update package repositories
#apt-get update

# Install Nginx
#apt-get install -y nginx

# Stop Nginx service
service nginx stop

# Update Nginx configuration
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/g' /etc/nginx/sites-available/default

# Start Nginx service
service nginx start

# Verify Nginx is running as nginx user
if pgrep -x "nginx" >/dev/null; then
  echo "Nginx is running as nginx user"
else
  echo "Failed to start Nginx with nginx user"
fi
